name: "Cached LFS checkout with submodules"

description: "Git checkout with LFS files from cache with submodules"

branding:
  icon: "download"
  color: "green"

inputs:
  repository:
    description: "Repository name with owner"
    required: false
    default: ${{ github.repository }}
  ref:
    description: "The branch, tag or SHA to checkout"
    required: false
    default: ''
  token:
    description: "PAT used to fetch the repository"
    required: false
    default: ${{ github.token }}
  path:
    description: "Relative path under $GITHUB_WORKSPACE to place the repository"
    required: false
    default: ''
  fetch-depth:
    description: "Number of commits to fetch. 0 indicates all history for all branches and tags"
    required: false
    default: '1'
  submodules:
    description: "Whether to checkout submodules. Accepted values are: true, false, recursive"
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Initialize Git LFS
      run: git lfs install
      shell: bash

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        token: ${{ inputs.token }}
        path: ${{ inputs.path }}
        fetch-depth: ${{ inputs.fetch-depth }}
        submodules: ${{ inputs.submodules }}

    - name: Pull LFS files
      run: git lfs pull
      shell: bash
    
    - name: Create LFS file list
      working-directory: ${{ inputs.path }}
      run: |
        git lfs ls-files -l | cut -d' ' -f1 > .lfs-assets-id
        git submodule foreach --recursive 'git lfs ls-files -l' | cut -d' ' -f1 >> .lfs-assets-id
        grep -v Entering .lfs-assets-id | sort > .temp
        mv .temp .lfs-assets-id
      shell: bash

    - name: Restore LFS cache
      uses: actions/cache@v4
      id: lfs-cache
      with:
        path: ${{ inputs.path }}/.git/lfs
        key: ${{ runner.os }}-lfs-${{ hashFiles('**/.lfs-assets-id') }}-v1

    - name: Git LFS Pull
      working-directory: ${{ inputs.path }}
      run: |
        git lfs pull
        git submodule foreach --recursive 'git lfs pull'
      shell: bash

    - name: Clean up
      working-directory: ${{ inputs.path }}
      run: rm .lfs-assets-id
      shell: bash
